### PR TITLE
Bump version and update maintainer

### PR DESCRIPTION
**Pull request by evanbattaglia**
Bump version for recent change to add `ReadTimeout` error. Also update maintainer. @b4hand , I assume you wish to be removed as maintainer. @lindseyreno , as you have experience with reppy, you have been volunteered.

### CODE REVIEW

**Comment by evanbattaglia** [comment]
@b4hand @dlecocq I believe one of you will need to add Lindsey or me as a maintainer on PyPI for us to complete the release? Can one of you do that? My username is `battaglia.evan`

**Comment by dlecocq** [comment]
Sure - I'll add you both. @lindseyreno - what's your Pypi username?

**Comment by lindseyreno** [comment]
Mine is lindsey.reno.

**Comment by lindseyreno** [comment]
And hi Dan!

**Comment by dlecocq** [comment]
@lindseyreno - hi! I've been glad to see your name pop up on the PR approvals!

Pypi won't let me add you and tells me "User 'lindsey.reno' does not have a verified primary email address and cannot be added as a Owner for project," like with Evan's. But once your emails are sorted with Pypi, I'll add you both!

**Comment by lindseyreno** [comment]
@dlecocq I guess it needed _both_ emails verified.  Should be all set now.

**Comment by dlecocq** [comment]
👍 - you should be all set now and have permissions to add folks as needed as well.

**Comment by lindseyreno** [comment]
Thanks!

**Pull request merged**
